package com.obu.tech.poba.utils.role;

public class Roles {
    // บุคลากร
    public static final String ROLE_PERSONNEL_INFO_PROFILE_ACCESS = "ROLE_PERSONNEL_INFO_PROFILE_ACCESS";
    public static final String ROLE_PERSONNEL_INFO_PROFILE_SEARCH = "ROLE_PERSONNEL_INFO_PROFILE_SEARCH";
    public static final String ROLE_PERSONNEL_INFO_PROFILE_ADD = "ROLE_PERSONNEL_INFO_PROFILE_ADD";
    public static final String ROLE_PERSONNEL_INFO_PROFILE_EDIT = "ROLE_PERSONNEL_INFO_PROFILE_EDIT";
    // ศึกษาต่อ แลกเปี่ยน
    public static final String ROLE_PERSONNEL_INFO_STUDY_ACCESS = "ROLE_PERSONNEL_INFO_STUDY_ACCESS";
    public static final String ROLE_PERSONNEL_INFO_STUDY_SEARCH = "ROLE_PERSONNEL_INFO_STUDY_SEARCH";
    public static final String ROLE_PERSONNEL_INFO_STUDY_ADD = "ROLE_PERSONNEL_INFO_STUDY_ADD";
    public static final String ROLE_PERSONNEL_INFO_STUDY_EDIT = "ROLE_PERSONNEL_INFO_STUDY_EDIT";
    // อาจารย์
    public static final String ROLE_PERSONNEL_INFO_RESEARCHER_ACCESS = "ROLE_PERSONNEL_INFO_RESEARCHER_ACCESS";
    public static final String ROLE_PERSONNEL_INFO_RESEARCHER_SEARCH = "ROLE_PERSONNEL_INFO_RESEARCHER_SEARCH";
    public static final String ROLE_PERSONNEL_INFO_RESEARCHER_ADD = "ROLE_PERSONNEL_INFO_RESEARCHER_ADD";
    public static final String ROLE_PERSONNEL_INFO_RESEARCHER_EDIT = "ROLE_PERSONNEL_INFO_RESEARCHER_EDIT";
    // ตำแหน่งบริหาร
    public static final String ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_ACCESS = "ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_ACCESS";
    public static final String ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_SEARCH = "ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_SEARCH";
    public static final String ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_ADD = "ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_ADD";
    public static final String ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_EDIT = "ROLE_PERSONNEL_INFO_ACADEMIC_SERVICE_EDIT";
    // ผู้สอนหลัก
    public static final String ROLE_TEACHING_ACCESS = "ROLE_TEACHING_ACCESS";
    public static final String ROLE_TEACHING_SEARCH = "ROLE_TEACHING_SEARCH";
    public static final String ROLE_TEACHING_ADD = "ROLE_TEACHING_ADD";
    public static final String ROLE_TEACHING_EDIT = "ROLE_TEACHING_EDIT";
    // วิทยากร
    public static final String ROLE_LECTURER_ACCESS = "ROLE_LECTURER_ACCESS";
    public static final String ROLE_LECTURER_SEARCH = "ROLE_LECTURER_SEARCH";
    public static final String ROLE_LECTURER_ADD = "ROLE_LECTURER_ADD";
    public static final String ROLE_LECTURER_EDIT = "ROLE_LECTURER_EDIT";
    // ป.ตรี
    public static final String ROLE_CONSULTANT_STUDENT_BACHELOR_ACCESS = "ROLE_CONSULTANT_STUDENT_BACHELOR_ACCESS";
    public static final String ROLE_CONSULTANT_STUDENT_BACHELOR_SEARCH = "ROLE_CONSULTANT_STUDENT_BACHELOR_SEARCH";
    public static final String ROLE_CONSULTANT_STUDENT_BACHELOR_ADD = "ROLE_CONSULTANT_STUDENT_BACHELOR_ADD";
    public static final String ROLE_CONSULTANT_STUDENT_BACHELOR_EDIT = "ROLE_CONSULTANT_STUDENT_BACHELOR_EDIT";

    // ป.โท เอก
    public static final String ROLE_CONSULTANT_STUDENT_MASTER_ACCESS = "ROLE_CONSULTANT_STUDENT_MASTER_ACCESS";
    public static final String ROLE_CONSULTANT_STUDENT_MASTER_SEARCH = "ROLE_CONSULTANT_STUDENT_MASTER_SEARCH";
    public static final String ROLE_CONSULTANT_STUDENT_MASTER_ADD = "ROLE_CONSULTANT_STUDENT_MASTER_ADD";
    public static final String ROLE_CONSULTANT_STUDENT_MASTER_EDIT = "ROLE_CONSULTANT_STUDENT_MASTER_EDIT";
}
